osdc.Rproj
Make it so we can build the documentation with `Ctrl-Shift-B` (the `PackageRoxygenize` line), make it so Markdown gets reformatted into canonical mode.
=> config: Small settings for working in the project on a package

.github/workflows/auto-author-assign.yaml
This PR adds a GitHub Action that automatically adds the author of the PR as assignee. 
Closes #38
=> feat: :sparkles: workflow that assigns PR author as assignee

vignettes/osdc.Rmd
Stacked PR. Start adding content to the getting started vignette. Very basic right now, but just to get it filling in.
`vignette("explanation")` doesn't exist yet, I am working on that.
=> docs: drafting first section of getting started vignette

.github/workflows/R-CMD-check.yaml, .github/workflows/build-package.yaml, .github/workflows/pkgdown.yaml, .github/workflows/test-coverage.yaml, README.md
Right now there are three Actions that run all at once. They often fail, which means I get three emails saying they failed. It makes more sense that they run in sequence, so I converted the existing ones into reusable actions (`workflow_call:`) and created one that sets them all in sequence (first `check`, then `coverage`, then `deploy`).
=> ci: improve action build process

.vscode/extensions.json, .vscode/settings.json
I followed some guidelines and suggestions from https://rolkra.github.io/R-VSCode/
- `levelOfObjectDetail` tells R to even search columns in a data object.
- `data.rowLimit` tells `View()` to only load the first 1000, rather than all the data.
- `useHttpgd` is a plot utility.
=> chore: 🧑‍💻 add settings to VS Code to improve R experience

.github/workflows/R-CMD-check.yaml
The action keeps failing, one of the reasons being that Pandoc isn't installed so that references can be added to the vignettes
=> ci: needs to install Pandoc to build the vignettes

.github/workflows/R-CMD-check.yaml
The Action needs the package dependencies that is only used when testing. Very small change.
=> ci: add testing package dependencies

vignettes/design.Rmd
Before: 
Now: 
I know it's a minor thing, but it annoyed me :)
=> fix: :art: add space before register_abbrev

.vscode/settings.json
... which is different from RStudio reformatting.
I have been fighting VS Code on the autosave and ended up doing this locally, so I thought I would add it here too.
=> fix: remove formatOnSave to avoid VS code reformatting

vignettes/data-sources.Rmd
... in the data sources vignette
=> added section on getting access to data

data-raw/algorithm.csv, tests/testthat.R, tests/testthat/test-include-hba1c.R
I'm starting by adding some tests without the actual code to test because I want to make sure we're on the same page with how the output should look like.
We can go over this during the meeting.
=> test: add some unit tests for hba1c inclusion

vignettes/function-flow.Rmd
Based on what has already been implemented for the HbA1c inclusion criteria, I have updated the documentation of this criteria in the function flow vignette. 
I have also added the `algorithm.Rda` to be able to show the logic in a table. I thought it might be nice to visualise it and make it rely directly on the algorithm logic that we implement.
However: 
1) I have probably added it in a very non-ideal / non-Luke-approved manner
2) I ended up writing it all in the text as well, so maybe it's not necessary to include at all?
=> docs: :memo: add details on HbA1c inclusion criteria

vignettes/changes.Rmd
Now includes simplified de-duplication of HbA1c and pregnancy definitions (see description in document) and the accuracy is slightly better overall, and particularly in the small, atypical groups (T1D old at diagnosis & T2D young at diagnosis). Very happy it turned out this way!
Closes #107, closes #74
=> docs: :memo: update with version 1.1 validation metrics

justfile
Closes #156
In order to use this, you will need to install justfile (https://just.systems/man/en/packages.html). Then, to run everything and make sure everything is good enough to be submitted to CRAN, run `just run-all`. Ideally we would run this right before creating a PR to minimize any GitHub build errors or issues.
=> build: :hammer: add justfile with full sequence of build steps to run locally

data-raw/simulate-data.R, data-raw/simulation-definitions.csv, data-raw/variable-description.csv
This PR changes the format of the variable `honuge` from `wwyy` to `yyww`, since that's the correct format, according to [DST](https://www.dst.dk/da/TilSalg/Forskningsservice/Dokumentation/hoejkvalitetsvariable/sygesikring---ydelser/honuge). I have changed this in the data simulation and variable description. 
I have also added a zero padding of the week number, since that's how it's described by DST (in the link provided above: 
> HONUGE er angivet som ÅÅUU, altså 2-cifret årstal efterfulgt af ugenummer 01 til 52 (evt. 53).
NOTE: this does not update the simulated data. I'll add that to the targets pipeline in a separate PR and update it there.
=> fix: 🐛 change honuge format to yyww

R/include-gld-purchases.R, man/get_algorithm_logic.Rd, man/include_gld_purchases.Rd, vignettes/data-sources.Rmd
This PR fixes the error and warnings thrown by the `R-CMD-check` workflow. 
This includes: 
- Changing `tidyverse` to `dplyr` in `data-sources.Rmd`
- Adding the missing `@param` `lmdb` for `include_gld_purchases()`
- Running `devtools::check()` that also updates the documentation (`.Rda` files).
=> fix: :bug: misc fixes to successfully run `r-cmd-check`

.github/workflows/reusable-document.yaml, .github/workflows/reusable-style.yaml
These changes are to fix the CI build that is failing to not find the branch to be able to push from. Plus fixed the commit messages to be conventional commit
=> ci: :construction_worker: don't need to install all package dependencies for styler

inst/WORDLIST, vignettes/articles/function-flow.Rmd
=> docs: :pencil2: fix lægemiddeldatabasen typos

justfile
=> build: :zap: change shebang to be more os independent

tests/testthat/test-columns-to-lower.R, tests/testthat/test-include-gld-purchases.R, tests/testthat/test-include-hba1c.R, tests/testthat/test-include-podiatrist-services.R, tests/testthat/test-joins.R, tests/testthat/test-verify-variables.R
The `as_duckplyr_tibble()` is deprecated, so need to update to `as_duckdb_tibble()`.
Doesn't need a review.
=> test: :white_check_mark: replace outdated function for duckdb

tests/testthat/test-include-hba1c.R
This kept popping up locally when I run `just run-all`
This PR doesn’t need a review.
=> style: :art: remove white space from include hba1c tests

R/algorithm.R
Bc I found out that an error is thrown when "!" is the first character in the logic when "no_potential_pcos" was used in `exclude_potential_pcos()`. Therefore, we might as well align it across the other criteria.
=> refactor: :recycle: change "!" to "NOT"

.Rbuildignore, DESCRIPTION
There were some notes in the CRAN check that this PR fixes. Plus, I ran `use_tidy_description()` to sort the imports in `DESCRIPTION`.
No need for a review.
=> build: :bug: fix notes from CRAN check and sort imports

R/classify-diabetes.R, R/exclude-potential-pcos.R
After I uncommented the first exclusion step, there was an error because the data for date is a string in the form YYYYMMDD. While we said to assume it is a date, if we also assume the variable is in the original format, it won't be a date. So this addition ensures the values are dates.
Closes #218 by not doing what is described in the issue.
=> feat: :sparkles: uncomment first exclusion step

justfile
Updating the wordlist should be intentional, not done as part of the build pipeline.
=> build: :fire: updating the wordlist shouldn't be automatically done

R/exclude-potential-pcos.R, R/include-gld-purchases.R, R/include-hba1c.R, R/include-podiatrist-services.R, R/joins.R, tests/testthat/test-joins.R
Since all our functions are internal to `classify_diabetes()`, which runs all the verifying there, we don't need to have the verifying in the internal ones.
=> refactor: :recycle: remove verifying from internal functions

R/algorithm.R, tests/testthat/test-include-podiatrist-services.R
@Aastedet and I had a chat about what `barnmak` actually means when it's 0 and 1, respectively. We found out the the logic needed to be swapped. See the meaning of the value in the `comments` in `algorithm.R`
=> fix(algorithm): :bug: `barnmak` logic in `podiatrist_services`

R/algorithm.R, R/prepare-lpr.R
This way it's aligned with what's done in `prepare_lpr3()` and all logic in these functions is in the algorithm.
I kept them separate (the one for lpr2 and lpr3) bc the column name differs.
=> refactor: :recycle: move lpr2 primary dx logic to algorithm

R/check-required-variables.R
To follow the Tidyverse style, as mentioned in #304
=> style: :art: remove explicit return in `check_required_variables()`

R/exclude-pregnancy.R, tests/testthat/test-exclude-pregnancy.R
We don't need `atc` variable after this point, so removing it.
=> refactor: :fire: no longer need `atc` after excluding pregnancy cases

tests/testthat/test-classify-diabetes.R, tests/testthat/test-exclude-potential-pcos.R, tests/testthat/test-exclude-pregnancy.R, tests/testthat/test-include-diabetes-diagnoses.R, tests/testthat/test-include-gld-purchases.R
To make other PRs smaller. This simplifies the tests and moves the main logic into the `classify_diabetes()` tests (which is where they should be.
=> test: :white_check_mark: simplify tests so most logic is in `classify_diabetes()`

justfile
It shows up in the terminal every time you run it which isn't very helpful once you have `air` installed :)
=> docs: :fire: remove comment in justfile `style` command

R/add.R, R/algorithm.R, R/classify-diabetes.R, R/exclude-potential-pcos.R, R/exclude-pregnancy.R, man/add_insulin_purchases_cols.Rd
This PR moved `add_insulin_purchases_cols()` down after exclusions so the columns are based only on the rows we keep (i.e., after removing purchases linked to potential PCOS or pregnancies).
I've also added an `any()` around the logic for `has_insulin_purchases_within_180_days` since I otherwise got a warning that `summarise()` was "returning more (or less) than 1 row per group" (see full warning message below). 
I found out that after moving `add_insulin_purchases_cols()` down, we have multiple rows with the same PNR in the simulated data, and with the logic "is_insulin_gld_code & date <= (first_gld_date + days(180))" I believe one logical would be returned per row. Since we want to know whether an individual has *any* purchases within 180 days, I thought `any()` was the right …
=> refactor: ♻️ move `add_insulin_purchases_cols()` down to after exclusions

vignettes/function-flow.qmd
Locally, they are black, but for some reason they turn blue on the website. So. I've established the `stroke` / edge colour to black explicitly now.
=> style: 💄 change edge colour to black in function flow diagram

R/classify-diabetes.R
I guess we forgot to remove cases where the NAs propagate and leads to NA in `has_t1d` and `has_t2d`. So this removes those rows.
=> fix: :bug: remove rows with NA in both T1 and T2D

R/drop.R
To keep rows from both `dropped_pcos` and `included_hba1c`. Otherwise, rows only in `included_hba1c` are dropped here.
=> fix: :bug: use `full_join()` instead of `left_join()`

R/algorithm.R
NAs will be propagated anyway (which is good), and in order for there to be a pregnancy event, there needs to be a pregnancy date. Plus, the `is.na()` is actually outside the `NOT`, which I think changes things.
=> fix: :bug: logic around `is.na()` in pregnancy event isn't needed
