steno-aarhus/osdc

DESCRIPTION
README.md

As well as small edits to the DESCRIPTION file.

Docs: Add explanations on what OSDC is in the README

---

.github/workflows/pr-commands.yaml
.github/workflows/test-coverage.yaml

CI: add test coverages actions and pull request helpers

---

.Rbuildignore
.github/CODEOWNERS
.github/workflows/pkgdown.yaml
.gitignore
CODE_OF_CONDUCT.md
DESCRIPTION
LICENSE.md
NEWS.md
README.md
_pkgdown.yml
inst/WORDLIST
osdc.Rproj
tests/spelling.R
tests/testthat.R
vignettes/design.Rmd

See the commit messages for what I did and what the commands I used were.

build: Setup basic package infrastructure and files

---

vignettes/design.Rmd

This is a "stacked PR", and depends on #31. Review and approve #31 first before this one. This PR adds some design principles to the design document.
Closes #36.

docs: first draft of design principles.

---

README.md

This is a "stacked PR", where changes are made to a "non-main" branch, so that it is easier to review. Please review and approve #31 first.

docs: small edits to the README file.

---

vignettes/design.Rmd

Is a "stacked PR", built on top of both #42 and #31. Please review and approve those first before reviewing this.
Closes #27.

docs: add use cases and core functionality of package

---

data-raw/variable_description.csv

Since we are not implementing original algorithm and the variable is no longer used.

Removed c_pattype variable from variable_description.csv

---

README.md

This PR adds a missing closing bracket to the `README.md`.

fix: add missing bracket

---

data-raw/value_description.csv

a csv file containing information on specific data points that need to be added or oversampled in addition to the overall/background distribution.

Description of algorithm-specific data values to oversample

---

.github/workflows/puml-to-svg.yaml

So we don't have to do it manually (ever again 🌟 )

ci: :construction_worker: add workflow to autogenerate images from pumls

---

vignettes/changes.Rmd

Validated the latest changes. I'll redo and re-add the 1.1 validation data, but the current one was not comparable to the others (it validated on a different (easier) random sample of the study population), so I removed it.

docs: :memo: small updates to the changes and validation doc

---

.github/PULL_REQUEST_TEMPLATE.md

Include a PR template to help with things.

chore: :technologist: include a PR template with a checklist to help remind us

---

.gitignore
justfile

chore: :brick: some infrastructural fixes

---

justfile
osdc.Rproj

These changes are fixing the justfile build that needs to install extra packages needed for targets.

build: :hammer: targets needs some extra things installed, which are in config/needs/data

---

R/get-variables.R
tests/spelling.R
tests/testthat/test-get-variables.R
tests/testthat/test-joins.R
vignettes/osdc.Rmd

style: :art: ran styler

---

justfile

And add it to `run-all` so we don't have to do this manually. 
Stacked on #196 .

build: ✨ add `update-wordlist` recipe

---

R/algorithm.R
man/algorithm.Rd
man/include_gld_purchases.Rd
man/include_podiatrist_services.Rd

Noticed this, it's a correction for the `seealso` note.
Doesn't need a review.

docs: :pencil2: small correction to `seealso` note

---

R/classify-diabetes.R
man/classify_diabetes.Rd

Since it's not ready yet + the R CMD checks fails bc of this example. Hopefully this fixes it 🤞

docs: :bulb: don't run examples section of `classify_diabetes()`

---

.vscode/settings.json
air.toml
justfile

Use the air formatter, not styler.
No review needed.

build: :hammer: add air formatter to vscode settings and justfile

---

README.md

Also fixed the instructions to install all dependencies.
Closes #189

docs: :memo: add explanation about using justfile

---

vignettes/articles/function-flow.Rmd

This reverts commit 6ef1e68db5614e8680507bfd008deb4b87786028.
This PR needs no review. 
Closes #264

Revert "docs: :memo: refer to function docs for `join_lpr2()` and `join_lpr3()` (#233)"

---

R/simulate-registers.R

Updated `air` locally and formatted `simulate-registers.R`, since it gave an error in a workflow in #273 
This PR needs no review.

style: :art: format `simulate-registers.R`

---

R/prepare-lpr.R
tests/testthat/test-prepare-lpr.R

Instead of `_department`
This PR needs no review.

refactor: :recycle: update `prepare_lpr2()` col names to be `_dept`

---

R/algorithm.R
R/exclude-potential-pcos.R
R/include-gld-purchases.R
R/include-hba1c.R
R/include-podiatrist-services.R
man/algorithm.Rd
man/get_algorithm_logic.Rd
tests/testthat/test-classify-diabetes.R

As agreed on in #290, I've renamed "criteria" to "logic". This lead me to also change some occurrences of "criteria" in other files. Let me know, if I went overboard ⛵ 
Closes #290

refactor: :recycle: `criteria` -> `logic`

---

vignettes/changes.Rmd

As we discussed at the meeting today, this change removes unnecessary complexity in the function flow.

docs 📜 : change to insulin purchase window to be evaluated from date of first purchase

---

DESCRIPTION
man/osdc-package.Rd

I wanted to add my ORCID bc I just registered, but then I realised that @Aastedet 's was missing as well. So, I've added both here 👌

chore: :mag: add ORCIDs for Signe and Anders

---

NEWS.md

Splitting this out of #296, it's getting too big.
Adding a note about using Commitizen and continuous releases to the NEWS file. Also did some touch ups.

docs: :memo: note about continuous release and some fixes in NEWS

---

man/select_required_variables.Rd

Came up when I ran `just run-all`.

docs: :memo: update ref docs for `select_required_variables()`

---

vignettes/function-flow.qmd

docs: :memo: simplify list of internal functions, link to their docs

---

.vscode/extensions.json

chore: :wrench: remove PlantUML extension recommendation

---

inst/WORDLIST

docs: :memo: update `WORDLIST`
